### ISSUE TITLE
Element being remove gets content changed.

### ISSUE THREAD

**Issue by rhernandog** [reactjs/react-transition-group#119]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
When removing an element from a list, the element's content or text in this case, is replaced by the one beneath it.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/m4mb9Lg3/4/).**
https://codesandbox.io/s/nB6rR2rP
Add three to four elements and then delete any except the last one (in that case it works). You'll see that the content of the element being removed is equal to the one below. In a local environment using react dev tools I see the element has already removed from the app's state but the key of the element in the DOM keeps being the same, what changes is it's content.

**What is the expected behavior?**
Obviously to keep the same content while removing the element.

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**
Chrome 59
Firefox 53
IE 11
OS: Windows 7 64
React Transition Group Version: 1.2

**Comment by jquense** [comment]
yes! you are running into the real reason for `key` in React. Since you are using the item's `index` for a key instead of a real identifier, when you delete an item in the middle, the item on top shift down and gets the same key (it's new index) as the item you removed. React thinks these are the same item and does some weird thing.

check out: https://facebook.github.io/react/docs/lists-and-keys.html for more info, but providing a key that sticks to the item regardless of location will fix the issue you are seeing
