### ISSUE TITLE
Trying to fade out element then slide up

### ISSUE THREAD

**Issue by no1melman** [reactjs/react-transition-group#129]
This is a question.

I've tried to create an animation of fading out an element then slide up the list. Here is my [question on stackoverflow](https://stackoverflow.com/questions/45304020/react-transition-group-slide-elements-up).

Here is [my codepen](https://codepen.io/no1melman/pen/XaJXdo?editors=0110)

I've been running into the problem that the element seems to get removed too quickly? and the `{ enter: 400, exit: 700 }` make no difference. I would have though that if I have my css animation in two stages with a combined duration of say 700ms, then if I set the `exit: 700` it should complete the animation before the element is removed...

**Comment by jquense** [comment]
Hi there, you have two issues with the codepen. The first is you aren't using a stable `key` for your list items, so removing something in the middle of the list won't work right. The second is that your setup is correct, and the `timeout` is working and the animation is playing, but you don't see the animation for height play because you can't animate from `height: auto` with plain css transitions.

here https://codepen.io/anon/pen/dzPvEO?editors=0110 is a working pen but it requires setting an explicit hieght on the items (max-height isn't enough). One way of dealing with this neatly in a dynamic manner is to use the `onExit` callback to measure and set the height on the exiting item so it has an explicit height set while exiting. This how the bootstrap Collapse component handles it btw: https://github.com/react-bootstrap/react-bootstrap/blob/next/src/Collapse.js#L150
