### ISSUE TITLE
A way to trigger appear animation using Transition

### ISSUE THREAD

**Issue by VladShcherbin** [reactjs/react-transition-group#133]
v2.2.0

```js
const IntransitionElement = (props) => {
  const defaultStyle = {
    transition: `opacity ${300}ms ease-in-out`,
    opacity: 0
  }

  const transitionStyles = {
    entering: { opacity: 1 },
    entered:  { opacity: 1 }
  }

  return (
    <p style={{
      ...defaultStyle,
      ...transitionStyles[props.state]
    }}>hey</p>
  )
}

class Test extends React.Component {
  state = {
    show: true
  }

  render() {
    return (
      <section>
        <Transition in={this.state.show} timeout={300} appear>
          {state => (
            <IntransitionElement state={state} />
          )}
        </Transition>
      </section>
    )
  }
}
```

The `IntransitionElement` `p` element has already opacity set to 1 when first rendered so the appear animation (from 0 to 1) is not working.

I read the docs probably like 10 times, but still don't understand, how is it possible to make it work?

**Comment by jquense** [comment]
Your code is mostly correct, the problem is you need to deal with the all the details of css animation yourself if you're going to use the Transition component (instead of the CSSTransition component). specifically you need to reflow the browser between the initial and entering state, otherwise the browser won't show the animation.

https://jsfiddle.net/m4mb9Lg3/8/

If you don't want to deal with these things, the CSSTransition component has essentially the same API as the old CSSTransitionGroup.

**Comment by VladShcherbin** [comment]
@jquense what's the difference between Transition and CSSTransition components? How do you choose, what component when to use?

**Comment by jquense** [comment]
The Transition component is a _generic_ component for tracking transition state over time; an abstract enter and exit. CSSTransition is for doing css animations, it's built on top of Transition. Like the v1 components one (CssTransition) is a high level api and the other low level for building different sorts of Transitions

**Comment by VladShcherbin** [comment]
@jquense oh, now I get it. CSSTransition will automatically add classNames for easy manipulation with css while Transition gives you more control over the flow.

Thank you for explanation.
