### ISSUE TITLE
How to avoid Transition child rerendering

### ISSUE THREAD

**Issue by VladShcherbin** [reactjs/react-transition-group#135]
v2.2.0

When `Transition` components `append`, `enter` or `exit` transition is executed, the child component is rerendered.

Here is the [example](https://jsfiddle.net/m4mb9Lg3/10/). In the console, you can see rerender log for append, on toggle click you can see additional rerenders.

How is it possible to reduce component rerendering?

**Comment by Horizon-Blue** [comment]
One way to avoid additional re-render is to use [`React.PureComponent`](https://facebook.github.io/react/docs/react-api.html#react.purecomponent) instead of a functional component as a child.

The child component will still be re-render when it is toggled from off to on though, because you choose to unmount it during exit. Other than that, there won't be any additional re-render.

**Comment by VladShcherbin** [comment]
@Horizon-Blue hey. I'm actually trying to create a React Router page transition like [here](http://animate.mhaagens.me), [article](https://hackernoon.com/animated-page-transitions-with-react-router-4-reacttransitiongroup-and-animated-1ca17bd97a1a).

Since the re-rendering component is actually a Route, it has a lot of props so using `PureComponent` or writing `shouldComponentUpdate` for underlying component is not an easy thing.

Currently, I have a component and try to animate it with `onEnter`, `onExit` hooks. I've seen, you also [tried](https://github.com/ReactTraining/react-router/issues/5279#issuecomment-313902078) similar thing with React Router 4, maybe you have a suggestion, how to create this page transition?

**Comment by VladShcherbin** [comment]
Moved to https://github.com/reactjs/react-transition-group/issues/136
