### ISSUE TITLE
if ReactTransitionGroup component's children component is returned by a higher-order component...

### ISSUE THREAD

**Issue by xuqinggang** [reactjs/react-transition-group#18]
question:
if ReactTransitionGroup component's children component is returned by a higher-order component, the children component's animated methods such as componentWillAppear can not be called.
e.g.
```
<ReactTransitionGroup>
     <ChildComponent>
</ReactTransitionGroup>
```

ChildComponent.js

```
@immutableRenderDecorator   //return a wrapped component by immutableRenderDecorator 
class ChildComponent extends Component {

}
export default ChildComponent;
```

question:  a wrapped component returned by immutableRenderDecorator don't have animated methods such as componentWillAppear。
if i have to use higher-order component to wrap ChildComponent, how ReactTransitionGroup improve to resolve this question?

**Comment by jquense** [comment]
that's correct, the TransitionGroup can't "see" the static methods because they are hidden inside another class. There really isn't much that can be done about that tho, I'd suggest not using an HOC in that case. generally this API is fairly low level and should be wrapped up by other components so consumers don't have this problem. look at how CssTransitionGroup handles it with `childFactory` a dedicated child component
