### ISSUE TITLE
Why is this not utilising ontransitionend events?

### ISSUE THREAD

**Issue by AndyOGo** [reactjs/react-transition-group#190]
**Do you want to request a *feature* or report a *bug*?**
feature | bug

**What is the current behavior?**
Timeouts have to be hardcoded for CSS transitions

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/m4mb9Lg3/4/).**

**What is the expected behavior?**
Timeouts should recognised automatically by utilising [ontransitionend](https://developer.mozilla.org/en-US/docs/Web/Events/transitionend) event.

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**
all

**Comment by jquense** [comment]
https://github.com/facebook/react/pull/4561

**Comment by AndyOGo** [comment]
@jquense 
Thanks for your quick response.
I'm curious if this is really the only solution, any other animation library I used so far manage to cope with `ontransitionend` event normalisation 🤔

**Comment by jquense** [comment]
Ideally we'd support both, but timeouts will always be required, so it was less of a priority to add in right now. The timeout approach is fairly common tho, bootstrap, for instance does it. so too the angular animate lib.

The api does allow some flexibility for implementing this [as I do here](https://github.com/jquense/react-widgets/blob/master/packages/react-widgets/src/SlideDownTransition.js#L31). Practically we probably won't do the duration parsing in the lib here tho, because it's not always the case that the root node is the one with the transition-duration specified.

**Comment by AndyOGo** [comment]
@jquense 
I see, thanks for your answer.
