### ISSUE TITLE
CSSTransition fade in-out example in the docs doesn't appear to work correctly

### ISSUE THREAD

**Issue by flushentitypacket** [reactjs/react-transition-group#289]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Example for CSSTransition at https://reactcommunity.org/react-transition-group/ only fades out, and not back in.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/m4mb9Lg3/4/).**

Example for CSSTransition at https://reactcommunity.org/react-transition-group/ only fades out, and not back in.

**What is the expected behavior?**

Should fade in, too. The current example is not as helpful as it should be

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**

Issue is present in both Chrome and Firefox from my initial test

**Comment by jacobstern** [comment]
Can @jquense or another contributor help out with this? I'm trying to upgrade from v1 and the CSS transition API is unusable if it doesn't properly hide the element before it is supposed to appear (as the example seems to demonstrate). Thanks!

**Comment by stawberri** [comment]
Um, I thought I'd share a workaround I think I found for this issue.

If you set a `{ unmountOnExit: true }` prop on your `CSSTransition`, it should unmount your component when it's meant to be hidden.

```js
<CSSTransition unmountOnExit in={active} {...otherProps}>{children}</CSSTransition>
```

I haven't tested this since `unmountOnExit` seemed to work well enough, but the next thing I was about to try was wrapping my `CSSTransition` in a conditional, and then putting that inside of a `TransitionGroup`. I think that might work as well, and it looks like it would match the v1 API better.

```js
<TransitionGroup>
  {active && <CSSTransition {...otherProps}>{children}</CSSTransition>}
</TransitionGroup>
```

**Comment by silvenon** [comment]
Hi! Thanks for the suggestions, I also wasn't happy with the examples so we updated the docs with new and more complex examples that hopefully better demonstrate how components could be used. 😉

**Comment by gl2748** [comment]
The example here is not appearing:
https://reactcommunity.org/react-transition-group/css-transition
