### ISSUE TITLE
What's wrong with this simple use case?

### ISSUE THREAD

**Issue by FezVrasta** [reactjs/react-transition-group#291]
**Do you want to request a *feature* or report a *bug*?**

bug?

**What is the current behavior?**

The exit animation doesn't work as expected

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/m4mb9Lg3/4/).**

https://codesandbox.io/s/93k3vnmvmp

**What is the expected behavior?**

The exit animation should work

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**

I have no idea, it doesn't work on any browser anyway.

**Comment by jquense** [comment]
Why is "weird" mode weird, thats the correct implementation. Your normal example doesn't change the opacity to 0 until the `exited` by which time the whole transition is already over. Set opacity to `0` on exiting, and then between exiting -> exited it fades out.

**Comment by FezVrasta** [comment]
So, my understanding was that `entering` and `exiting` were applied when the transition begins, and `exited` and `entered` were applied at the end...

if this is not the case, why do I need two states?

**Comment by jquense** [comment]
You are right that is the case, so in your exiting case you _begin_ the transition by setting the opacity to 1, it's already 1 though, so nothing happens. CSS transitions work by setting the end value and letting the browser animate from the previous value to the one you just set. Here is your example simplified without the unneeded TransitionGroup it should illustrate which styles are being applied and when: https://codesandbox.io/s/mzq2rp5yqp

**Comment by FezVrasta** [comment]
Umh...

Doing as you say, if you use `TransitionGroup`, the `enter` animation doesn't work.

https://codesandbox.io/s/j36n9jxxn3

My understanding was that:

- `entering` => set opacity to 0, ready to perform the transition
- `entered` => set opacity to 1, transition begins
- `exiting` => set opacity to 1, ready to perform transition
- `exited` => set opacity to 0, transition begins

But with what you say then I don't understand how to make this last example work (with `TransitionGroup`)

**Comment by jquense** [comment]
I don't know why you are using the TransitionGroup there, that's the wrong use of it. If you are animating one thing in and out you just use Transition

> My understanding was that: [...]

Sorry then no that's not correct

- entering => The animation begins
- entered => the animation ends
- exiting => The animation begins
- exited => the animation ends

**Comment by FezVrasta** [comment]
How can I make the element appear and disappear from the DOM when it's not visible then? That's what I'm using `TransitionGroup` for.

**Comment by jquense** [comment]
You can use `unmountOnExit` and `mountOnEnter`, That case is slightly more complex because CSS transitions are weird and you need to handle their idiosyncracies

https://codesandbox.io/s/mzq2rp5yqp

**Comment by FezVrasta** [comment]
Thanks for your help... I have to say that from the documentation all this stuff is very confusing, and at the end, the suggested way (yours) at the end is confusing as my original example... (because you don't actually use the two states)

**Comment by jquense** [comment]
That's not quite right, all the states are being used in my examples. You can see from https://codesandbox.io/s/mzq2rp5yqp (without the unmounting/mounting) that it starts with in={false}` so the state is `exited` as in "This is currently in the exited state". If you removed the style for exited the item would fade to opacity 0, then pop back in, because the default opacity of a DOM element is `1`. Remember the API is *not* imperative, you aren't telling it how to go from state to state, you're declaratively telling the element what styles it should have at any given state. Another way of saying it is that each state is *not* a callback, its a state the element _stays_ in untill you move it to another one.

The case where the element is not mounted when it's exited is a bit special because the element is removed so it can't be styled. So yes in that _particular_ case you don't need the `exited` state, but only because the element doesn't exist.

**Comment by FezVrasta** [comment]
![image](https://user-images.githubusercontent.com/5382443/36268233-48d762c4-1276-11e8-9c5f-f43f9e82698b.png)

Why do you have the same values on `entering` and `entered`?

**Comment by jquense** [comment]
thats how css transitions work, You set the value you want to end with at the start of the transition. setting to `1` changes it from `0.25` it then transitions from `.25` -> `1` over 2 seconds. At `entered` opacity is 1 because you want it to _continue_ to be visible yes? Otherwise no style is applied and whatever the default css value is will take over. The opacity will be unspecified. That may work, because `1` is the default value, but what if you have some other css, better to be explicit.

**Comment by silvenon** [comment]
Hey Federico, just in case things are still not clear, I sent you a tweet a while ago about this. https://twitter.com/silvenon/status/973883053666918400?s=20

Sometimes it's easier to use `CSSTransition` when you need the [reflow hack](https://blog.silvenon.com/the-nuances-of-react-transition-group-9214b2302138) (usually on entering animations). I updated your example with comments. https://codesandbox.io/s/k97qkmkrqv

Let me know if you still have questions.
