### ISSUE TITLE
Make a different package for the v1

### ISSUE THREAD

**Issue by VinceBT** [reactjs/react-transition-group#298]
Currently I'm using this component in the v1 version with react-native, and it works really great.

But whenever I'm updating my packages, it updates to v2 and I get errors.

Would it be possible to split the package in two different packages like ```react-transition-group``` for v1 and ```react-css-transition-group``` for v2 ?

**Comment by jquense** [comment]
At the point we couldn't make v2 a different packet since the latest version of it is v2. Ultimately tho I don't think we'd do it if we could. V1 is old and done, and we aren't gonna make any more changes to it. It'll continue to work, but we recommend that people eventually migrate to the last version

**Comment by jquense** [comment]
I'd also recommend setting your version range tho to something that doesn't accept major bumps so you don't have it automatically update
