### ISSUE TITLE
Disappear Transition

### ISSUE THREAD

**Issue by mateeyow** [reactjs/react-transition-group#30]
**Do you want to request a *feature* or report a *bug*?**
*FEATURE*

**What is the expected behavior?**
An animation/transition that activates when a component disappears or unmounts

**Comment by jquense** [comment]
Hi, thanks for the suggestion. Unfortunately this isn't possible simply. Components can't, themselves animate on unmount because they cannot cancel or unmount asynchronously. You'd have to wrap the group in its own transition component. The proposed new API should make this easier tho! Please weigh in on the PR https://github.com/reactjs/react-transition-group/pull/24

**Comment by BowserKingKoopa** [comment]
This is my biggest pain point with React.

**Comment by jquense** [comment]
I don't disagree! The generic Transition component proposed in #24 though should at least give a simple straightforward way to deal with this. It's a state machine that manages a component mount state over time.
