### ISSUE TITLE
Question about react-transition-group calling multiple render()

### ISSUE THREAD

**Issue by vegetablesalad** [reactjs/react-transition-group#344]
I implemented **react-transition-group** and it seems to work great. Only problem is it forces my component to be re-rendered four times when animating it in view? Is this correct or have I messed something up? All the props and states seem to be identical as far as I have figured out. What could be the reason for it to render it four times ?

**Comment by jquense** [comment]
yes that's correct. Internally Transition tracks it's progress through the transition via state, so you see a re-render as it transitions into the various states. More generally tho, React re-renders components allll the time, any time the component, or a parent changes. Probably that doesn't cause any issues since React is designed to make each render very cheap. If your component is making assumptions about how many times it renders, its probably designed poorly, components shouldn't have to think about that, and only in rare perf cases need to even optimize it with something like `shouldComponentUpdate`

**Comment by xusai2014** [comment]
@jquense 
Hi, guys. I understand that using re-renering implements the transition. But I happened  that repeat to send request. For examle:
```
<TransitionGroup>
        <CSSTransition
          key={location.key}
          classNames="fade"
          timeout={300}
        >
        { childern } 
        </CSSTransition>
      </TransitionGroup>
```
how to avoid the questions？Please give  me help. if you have any questions ,you can @ me. THX
