### ISSUE TITLE
Nested Transitions in TransitionGroup ignoring in-prop

### ISSUE THREAD

**Issue by RT-TL** [reactjs/react-transition-group#357]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

I nested several Transition-children inside a TransitionGroup element. They are always displayed, independent of their in-prop. This is even the case if I always pass "false" as prop.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [CodeSandbox](https://codesandbox.io/) or similar (Template: https://codesandbox.io/s/lvnpplww9).**

Here is sandbox of the issue: https://codesandbox.io/s/40vq0x53lw

**What is the expected behavior?**

Changing the in-prop of the nested Transition effects should trigger their entry/exit animation.

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**

Chrome/MacOS at least.

Reading through the issues I assume that this problem has something to do with the childFactory and can be solved this way. If so please help me fixing my example. I will then happily update the sandbox to share with others having the same issue.

**Comment by jquense** [comment]
See https://github.com/reactjs/react-transition-group/issues/350 you aren't really nesting transitions, its the single layour of ones defined by the Transition components. In this case you don't need the TransitionGroup, it's not adding anything since you are trying to manually control when each of the elements is in or out. I'd remove it and render only the `ul`
