### ISSUE TITLE
Error on `yarn run storybook`

### ISSUE THREAD

**Issue by SeanSilke** [reactjs/react-transition-group#369]
`yarn run storybook` leads to error `TypeError: plugins.extractText is not a function`
and storybook did not start.

**Comment by silvenon** [comment]
What is your version of Node? I'm errors for JSX and class properties, which also prevents the stories from rendering, but I'm curious about where your error is coming from.

**Comment by SeanSilke** [comment]
@silvenon node version is v8.11.3

**Comment by MannyC** [comment]
Yeah, storybook isn't working at all for me.

I did some investigation but ended up giving up.   Basically, the react-transition-group storybook isn't compatible with webpack 4, but the project itself has been bumped to use 4.

plugins.extractText seems to have been removed form `webpack-atoms`, probably because it wasn't compatable with webpack 4 ( see [here](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/701) ).  You can alter RTG to use `extract-text-webpack-plugin` directly, although they actually recommend using `mini-css-extract-plugin` instead for webpack 4 so I tried that.  That errored out for me, and because I don't know where all this is sitting within the overall project, I just left it.

**Comment by silvenon** [comment]
@jquense do you use Storybook when developing react-transition-group? I stopped using it a long while ago in general because I find it too much of a hassle, I just use `yarn link` instead. But I can try to revive Storybook if you think it's a good idea to keep it. Otherwise we could delete it.

**Comment by pajtai** [comment]
Is there an alternative way to look at demos? I couldn't get it to run either.

**Comment by pajtai** [comment]
To answer my own question and to others for reference, the docs have codebox examples.

So each of the following pages lets you see the transitions and play with them:

1. http://reactcommunity.org/react-transition-group/transition/
1. http://reactcommunity.org/react-transition-group/css-transition/
1. http://reactcommunity.org/react-transition-group/transition-group/

**Comment by cabinhero** [comment]
OK, I found a method to walk around the error, That's just remove the code like this.
![image](https://user-images.githubusercontent.com/31085313/45263319-bebdd100-b459-11e8-8058-5b8e93ff5129.png)

**Comment by emwalker** [comment]
If the storybook is broken and a "wontfix," perhaps a documentation update to remove the reference to the storybook?

**Comment by silvenon** [comment]
Works now 👍
