### ISSUE TITLE
When is the Transition component useful?

### ISSUE THREAD

**Issue by silvenon** [reactjs/react-transition-group#372]
Is there a common use case for the `Transition` component in the browser? How does it look like when used with React Native? Could we add a good example in the docs?

**Comment by silvenon** [comment]
The reason why I want us to make this clear is because I see people often using `Transition` when they meant to use `CSSTransition`.

**Comment by jquense** [comment]
The use case is generally low level. You'd use it to integrate with GSAP or [velocity-react](https://github.com/google-fabric/velocity-react). I've also used it for more abstracts things like hiding components after a timeout but without animation 

We should probably adjust the messaging again since, yeah it seems clear that most folks who want an out-of-the-box animation component really want the CSSTransition

**Comment by alanbuchanan** [comment]
@jquense Do you happen to have an example codesandbox of using `<Transition>` with GSAP or velocity-react?

**Comment by jquense** [comment]
@alanbuchanan velocity-react _is_ an example, its built using Transition 👍

**Comment by silvenon** [comment]
Should be more obvious with recent documentation updates.
