### ISSUE TITLE
Enable animation delay ?

### ISSUE THREAD

**Issue by hassanshaikley** [reactjs/react-transition-group#411]
How does one set transition delay? If that isn't possible can we request that feature.

`animation-delay` is a css property that doesn't seem to work with CSSTransition. Please make it work or give us an alternative!

I want some animations to play after 200ms, and some to play instantly.

**Comment by silvenon** [comment]
Is setting state using `setTimeout` not acceptable?

**Comment by jquense** [comment]
Or use animation-delay and have the time out be the duration plus the delay

**Comment by georgschlenkhoff** [comment]
Agree @jquense, I would appreciate a component property animation-delay that translates its value to [CSS prop `transition-delay`](https://www.w3schools.com/cssref/css3_pr_transition-delay.asp), @silvenon.

**Comment by silvenon** [comment]
Could you explain what's the difference? Is the problem duplicating the timeout duration in JS and CSS?

**Comment by skyboyer** [comment]
I'm not sure if I better to report new issue. But I cannot follow @jquense's suggestion.

here I've forked example from docs:     https://codesandbox.io/s/transitiongroup-component-v99xw

`timeout` for `CSSTransition` is sum of `transition-delay` + `transition-time`. But you can see animation starts immediately after clicking "X" button. `transition-delay` value is just ignored. 

At least it happens this way in Chrome@MacOS 10

**Comment by silvenon** [comment]
@skyboyer thanks for providing a demo 🏆 It makes it so much easier for us to understand what you're trying to do. In this case there are two main things going on:

1. You're passing a single value for the `timeout` prop, but your CSS counts on two different durations for enter (500ms) and exit (2500ms) transitions

2. You're setting `transition-delay` in `.item-exit`, but then you're implicitly overwriting it in `.item-exit-active` by using the [`transition` shorthand](https://developer.mozilla.org/en-US/docs/Web/CSS/transition), which sets `transition-delay` to `0`.

You can fix the 1st issue by passing `timeout={{ enter: 500, exit: 2500 }}` instead of `timeout={2500}`, to match your CSS. The 2nd issue can be fixed by simply passing the delay along with other values in the shorthand:

```css
transition: opacity 500ms ease-in 2s;
```

If you omit `2s`, `transition-delay` will be set to `0`, that's its initial value. This is a common misconception with using CSS shorthands, but it's important to know that this:

```css
transition-delay: 2s;
transition: opacity 500ms;
```

implicitly sets every other transition property to `initial`, which evaluates to something like this:

```css
transition-delay: 2s;
transition-property: opacity;
transition-duration: 500ms;
transition-timing-function: ease;
transition-delay: 0s; /* overrides the first transition-delay! */
```

**Comment by maaajo** [comment]
Hi!

Here is my TransistionComponent:
```
 <TransitionGroup>
   <CSSTransition key={uuidv4()} timeout={1000} classNames="slide">
     <GameQuestions
       gameOption={this.props.option}
       answers={this.state.answers}
       questionName={this.answer.name}
       handleUserAnswer={this.handleUserAnswer}
     />
   </CSSTransition>
</TransitionGroup>
```

Here is the css:

```
.slide-enter {
  opacity: 0;
  transform: scale(0.97);
  z-index: 1;
}

.slide-enter.slide-enter-active {
  opacity: 1;
  transform: scale(1) translateY(0);
  transition: opacity 300ms linear 1000ms, transform 300ms ease-in-out 1100ms;
}

.slide-exit {
  opacity: 1;
  transform: scale(1) translateY(0);
}

.slide-exit.slide-exit-active {
  opacity: 0;
  transform: scale(0.97) translateY(5px);
  transition: opacity 150ms linear 1000ms, transform 150ms ease-out 1000ms;
}

.slide-exit-done {
  opacity: 0;
}
```

The GameQuestions component which is animated here depends on a setState action which is delayed for lets say 1s. What I would like to achieve here is that the whole CSSTransition starts after 1s, not immediately like it is now. Would appereciate your help!
