### ISSUE TITLE
Block exiting until entered is done on Transition Component

### ISSUE THREAD

**Issue by eddiewang** [reactjs/react-transition-group#463]
Right now, it appears that if `in` is toggled, it immediately triggers the `Exiting` state, even if the `Entering` state has not been set to `Entered` yet.

Is there anyway to wait for the `Entering` state to complete before triggering the `Exiting` state?

**Comment by taion** [comment]
What does that mean, though? Like, to delay starting the transition out until the transition in finishes?

**Comment by eddiewang** [comment]
Exactly that. We have callbacks available with `done` using `addEndListener` but it isn't blocking, meaning if we quickly toggle between states it simply jumps from `entering` to `exiting`, and doesn't wait for the `entering` transition to complete.

**Comment by taion** [comment]
I'm not sure that makes sense to handle generically here – more commonly, i'd think people would want things to immediately start hiding when they're set to hide. Perhaps wrapping these to delay updates to loading state until entering is complete in your own code would make more sense.

**Comment by silvenon** [comment]
@eddiewang this library is meant to be used with CSS Transition and mimic its behavior, and CSS transitions don't wait for transitions to be over before transitioning back. Wanting this behavior seems pretty rare, you usually want exactly the opposite.

I created an [example solution](https://codesandbox.io/s/y3owmvz77z) for this, I achieved this by simply throttling the function that toggles the `in` prop. Just make sure you call `throttle` only once, not on each render otherwise it won't work as expected. (I.e. if you were to implement this using hooks, you'd need to memoize it using `useCallback` and passing an empty array `[]` to ensure it's only created once.)
