### ISSUE TITLE
CSSTransitions behaving incorrectly after upgrade from V1

### ISSUE THREAD

**Issue by therionus** [reactjs/react-transition-group#595]
I was trying to migrate my image carousel from v1 of ReactCSSTransitionGroup which was very straightforward until I realised there is a huge bug after migration.

As images can slide left and right, I had a flag "isNext" which is set to true when clicked on right arrow. And when clicked on left it nicely goes backwards. At least in the old version. The new one messes up until opposite direction is clicked again (try going both directions)

Here's new and old implementation example.
https://codesandbox.io/s/carousel-demo-fys8m

Anyone knows how to fix this? Or is it a bug?

**Comment by taion** [comment]
This is a timing issue on your end. In the new implementation, you're simultaneously unmounting the old slide while trying to set `isNext`... but because it's getting unmounted (because there's less arbitrary delay in the current version), the new value doesn't pass through. You may want to instead apply the next / prev style on the parent, or else not unmount non-shown slides.
