### ISSUE TITLE
Alternative to component and className props from CSSTransitionGroup?

### ISSUE THREAD

**Issue by lstanard** [reactjs/react-transition-group#711]
I'm migrating from version `1.1.3` to `4.4.1`. Previously `CSSTransitionGroup` accepted a `component` prop for providing a specific element to render as, rather than a `div`, as well as `className` for applying custom classes. It appears both of these features have been removed in the latest version. Is there an alternative method I'm missing for achieving this same result? 

Given that "component" and "prop" are such common keywords it's been difficult to effectively search and find results for these questions. I apologize if this has been covered elsewhere in documentation or previous issues.

**Comment by koba04** [comment]
@lstanard This is a migration guild from v1 to v2.
https://github.com/reactjs/react-transition-group/blob/master/Migration.md

`CSSTransitionGroup` has been removed and it can be replaced with `TransitionGroup` and `CSSTransition`.
The `component` prop is not required because `CSSTransition` doesn't create any component, so you can put any component as a child component of `CSSTransition` like the example. 
https://reactcommunity.org/react-transition-group/css-transition

To customize the className, you would use the `classNames` prop.
https://reactcommunity.org/react-transition-group/css-transition#CSSTransition-prop-classNames
