### ISSUE TITLE
using `unshift` to animate the first item in the array

### ISSUE THREAD

**Issue by johhansantana** [reactjs/react-transition-group#80]
Hello, I have a "news feed" that pushes new content at the beginning of the array of objects.

When I use `array.unshift(newPost)` it will add the item at the beginning but will animate/transition effect the last item in the array, always.

In what way can I make the first item in the array have the transition?

*edit*

I've tried using `array.reverse().map(...)` but it still doesn't work

**Comment by Setsun** [comment]
React utilizes the `key` prop on components to determine if a component has unmounted or needs to be updated. If the key is stable, then using `Array.unshift` on the array you are using for rendering should only animate in the first item in the array, since it knows to mount that exact component.

One potential gotcha for defining keys is that using the `index` of the array item in the key will always result in an inherently unstable key.

Potentially to get what you want you'll need to define a stable key for each component you have in your `TransitionGroup` if you are using `react-transition-group` 1.x.x.

### Example
```
render() {
  const posts = [
    {
      title: 'Poop',
      timestamp: 1234567
    },
    {
      title: 'Pooper',
      timestamp: 928323
    },
  ];

  return (
    <CSSTransitionGroup>
      {posts.map((post) => {
        const uniqueKey = `${post.title}-${post.timestamp}`;

        return (
           <div key={uniqueKey}>
               {post.title}
           </div>
        );
      })}
    </CSSTransitionGroup>
  )
}
```

**Comment by johhansantana** [comment]
oh I see, thanks for the clarification!

**Comment by lstuartfry** [comment]
For anyone in the future running into this issue, I highly recommend the npm package 'uuid.'  If you're running into issues where your items don't actually contain anything that is 100% unique, this package helps you avoid having to come up with your own solutions (which aren't always foolproof).

https://www.npmjs.com/package/uuid
