### ISSUE TITLE
animating a single element on leave

### ISSUE THREAD

**Issue by golanh** [reactjs/react-transition-group#88]
I have a page displaying several objects, which go through some filters (every filter changes the state of the array - cant do it otherwise). Each object in my array is an auction that contains several information including a timer. 
I want to avoid the activation of the leave animation when i search my db and activate it only when the timer finishes.

home component:

    eachAuction(item, i) {
        return <Auction key={i} index={i} auctionfinished={this.deleteAuction}
                offerBid={this.offerBid} data={item} />
    }

    render:
    <div>
        <CSSTransitionGroup
         transitionName="auction"
         transitionAppear={true}
         transitionAppearTimeout={700}
         transitionEnterTimeout={700}
         transitionLeaveTimeout={500}>
         {this.state.auctionsArr.map(this.eachAuction)}
        </CSSTransitionGroup>
    </div>

**Comment by jquense** [comment]
The `v1` Api doesn't make what you want to do easy, since the GRoup component is in charge of the transition. You can do it but you will have to essentially write your own CSSTransitionGroup. The `v2` API, however, should allow for this fairly straightforwardly by wrapping the components and passing in a toggle for when to turn on the leave animation for each child.

**Comment by golanh** [comment]
i couldnt find anything about this in the readme, can you show me an example regarding the toggle?

**Comment by jquense** [comment]
there isn't a specific API for it, you can check out the v2 stories and comments in the source to get an idea
