### ISSUE TITLE
Toggling between components triggers strange status

### ISSUE THREAD

**Issue by dan-lee** [reactjs/react-transition-group#90]
**Do you want to request a *feature* or report a *bug*?**
Bug(?)

**What is the current behavior?**
When exchanging two components via state (`Main` and `Overlay` in my case) underneath a `TransitionGroup` and `Transition` I get a strange sequence of status.
I logged my components names and the returned status returned:

> Main exited
Overlay entered
Overlay exiting
Main entering
Overlay exited
Main entering
Main entered

(See the Code Sandbox project linked below)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/1Lb2qk3v/).**

**https://codesandbox.io/s/mQx8L5N8E**

**What is the expected behavior?**
I expect `Overlay` (the first mounted component) to be exiting and `Main` to be entering.
Something like:

> Overlay exiting
Main entering
Overlay exited
Main entered

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**
v2.0.0-beta.1

**Comment by jquense** [comment]
Yeah that's to be expected. A component may re-render for other reasons than it's internal state changing. What you are seeing is the components rendering multiples times as the TransitionGroup updates various bits of state to move them in and out. It doesn't mean they've transitioned more times then you want. e.g. you see `Overlay entered` because the component rendered again before it's state switched to `exiting`.

If you want callbacks that only fire when the component actually switches a state then you can use the onEnter, onEntering, etc callbacks. They only fire once per state shift.

**Comment by dan-lee** [comment]
Okay I get it, thanks for the explanation!
So my understanding is that I can't use a FAC reliably to apply styles on my underlying components?

**Comment by jquense** [comment]
no you absolutely can use it reliably and should. Remember that react component renders aren't imperative. just because it renders multiple times doesn't mean anything is changing. Nothing is called out of order, it _may_ be called more than once.

**Comment by dan-lee** [comment]
You have been very helpful, thank you very much!
BTW: Great library, this is a hard task to solve (at least for me). So please keep on going :) 🚀

I guess I can close this now :)

**Comment by axe-z** [comment]
I get the same thing I have a transition between Routes, but if one of my route has render stuff like this : 
```
class Test extends Component {
    render() {
      let transformTest = 'test'
       console.log(transformTest)  //this get's outputted 4 times ! when a switch Routes
      return (
   ...
```
I get 24 fps average on firefox. Not sure what creates that echo/loop . 4 re-render is not what we should aim.
